language: cpp

sudo: required
dist: trusty

env:
  global:
    - SDK_INSTALL_PREFIX="$HOME/uroot/usr/local"
    - LD_LIBRARY_PATH="$SDK_INSTALL_PREFIX/lib:$SDK_INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"

before_install:
  - sudo apt-add-repository -y ppa:beineri/opt-qt542-trusty
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt54base qt54quick1 qt54tools qt54webkit qt54xmlpatterns
  - sudo apt-get install -qq liblog4cxx10 liblog4cxx10-dev
  - sudo apt-get install -qq libwrap0 libwrap0-dev

install:
  - . /opt/qt54/bin/qt54-env.sh
  - wget --directory-prefix=$HOME http://trueta.udg.edu/apt/ubuntu/devel/0.13/Starviewer-sdk-linux-0.13-0.tar.xz
  - mkdir ~/uroot
  - tar xf ~/Starviewer-sdk-linux-0.13-0.tar.xz -C ~/uroot

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - cd starviewer
  - qmake
  - make -j3
  - cd tests/auto
  - ./autotests
